export const restaurants = [
  {
    id: 1,
    name: "Dalma",
    image: require('../assets/images/dishes/download (2) (3).jpeg'),
    stars: 4.5,
    reviews: 1200,
    description:
      "Dalma is a popular vegetarian restaurant known for its authentic Odia cuisine. They offer a wide variety of thalis and traditional dishes.",
    category: "Odia",
    address: "Sahid Nagar, Bhubaneswar",
    time: "11 AM - 11 PM",
    distance: "2.5 km",
    dishes: [
      {
        id: 101,
        name: "Dalma",
        price: 180,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "A lentil stew cooked with seasonal vegetables and spices.",
        veg: true,
        egg: false,
      },
      {
        id: 102,
        name: "Macha Besara",
        price: 150,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Spicy fish curry cooked with mustard paste and vegetables.",
        veg: false,
        egg: false,
      },
      {
        id: 103,
        name: "Pakhala",
        price: 80,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "A fermented rice dish served chilled, perfect for a light meal.",
        veg: true,
        egg: false,
      },
      {
        id: 104,
        name: "Ghanta",
        price: 120,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Sweet pancakes made with rice flour and jaggery.",
        veg: true,
        egg: false,
      },
      {
        id: 105,
        name: "Chhenapoda",
        price: 100,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "A baked cheese dessert flavored with cardamom and saffron.",
        veg: true,
        egg: false,
      },
      {
        id: 106,
        name: "Aloo Posto",
        price: 140,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Potatoes cooked in poppy seed paste with a hint of sweetness.",
        veg: true,
        egg: false,
      },
      {
        id: 107,
        name: "Santula",
        price: 200,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "A mixed vegetable dish cooked in a creamy cashew paste.",
        veg: true,
        egg: false,
      },
      {
        id: 108,
        name: "Badi Chura",
        price: 110,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Sun-dried lentil fritters served in a yogurt curry.",
        veg: true,
        egg: false,
      },
      {
        id: 109,
        name: "Khaman",
        price: 90,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "A steamed gram flour cake with a savory and tangy taste.",
        veg: true,
        egg: false,
      },
      {
        id: 110,
        name: "Dahibara Aloo Dum",
        price: 130,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Fried lentil dumplings served in a potato curry with yogurt.",
        veg: true,
        egg: false,
      },
    ],
  },
  {
    id: 2,
    name: "Barbeque Nation",
    image: require('../assets/images/dishes/download (2) (3).jpeg'),
    stars: 4.2,
    reviews: 2500,
    description:
      "Barbeque Nation is a popular chain restaurant offering a live grill experience with a variety of grilled meats, seafood, and vegetables.",
    category: "Grill",
    address: "Jaydev Vihar, Bhubaneswar",
    time: "12 Noon - 11 PM",
    distance: "4.0 km",
    dishes: [
      {
        id: 201,
        name: "Chicken Skewers",
        price: 350,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Marinated chicken pieces grilled to perfection on skewers.",
        veg: false,
        egg: false,
      },
      {
        id: 202,
        name: "Prawns in Garlic Butter",
        price: 420,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Fresh prawns tossed in a flavorful garlic butter sauce.",
        veg: false,
        egg: false,
      },
      {
        id: 203,
        name: "Tandoori Paneer",
        price: 280,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Cottage cheese marinated in yogurt and spices, grilled in a tandoor.",
        veg: true,
        egg: false,
      },
      {
        id: 204,
        name: "Honey Glazed Drumsticks",
        price: 380,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Chicken drumsticks marinated and grilled with a sweet and sticky honey glaze.",
        veg: false,
        egg: false,
      },
      {
        id: 205,
        name: "Grilled Vegetables",
        price: 250,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "A selection of seasonal vegetables grilled to perfection.",
        veg: true,
        egg: false,
      },
      {
        id: 206,
        name: "Fish Tikka",
        price: 400,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),

        description: "Marinated fish pieces grilled in a tandoor.",
        veg: false,
        egg: false,
      },
      {
        id: 207,
        name: "Pineapple Raita",
        price: 120,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "A refreshing yogurt-based side dish with chopped pineapple.",
        veg: true,
        egg: false,
      },
      {
        id: 208,
        name: "Garlic Naan",
        price: 80,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Leavened flatbread flavored with garlic butter.",
        veg: true,
        egg: false,
      },
      {
        id: 209,
        name: "Mutton Seekh Kebab",
        price: 450,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Minced lamb kebab grilled on skewers.",
        veg: false,
        egg: false,
      },
      {
        id: 210,
        name: "Dal Makhani",
        price: 220,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Black lentil curry cooked with butter and cream.",
        veg: true,
        egg: true,
      },
    ],
  },
  {
    id: 3,
    name: "Aama Odia Hotel",
    image: require('../assets/images/dishes/download (2) (3).jpeg'),
    stars: 4.0,
    reviews: 1800,
    description:
      "Aama Odia Hotel is a family-run restaurant serving traditional Odia home-style cooking in a casual setting.",
    category: "Odia",
    address: "Cuttack Road, Bhubaneswar",
    time: "10 AM - 10 PM",
    distance: "1.8 km",
    dishes: [
      {
        id: 301,
        name: "Veg Thali",
        price: 200,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "A platter with a selection of vegetarian Odia dishes like dal, rice, vegetables, and chutney.",
        veg: true,
        egg: false,
      },
      {
        id: 302,
        name: "Mutton Curry",
        price: 320,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Spicy mutton curry cooked with traditional Odia spices.",
        veg: false,
        egg: false,
      },
      {
        id: 303,
        name: "Chhena Poda",
        price: 80,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "A baked cheese dessert flavored with cardamom and saffron.",
        veg: true,
        egg: false,
      },
      {
        id: 304,
        name: "Macha Besara",
        price: 180,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Spicy fish curry cooked with mustard paste and vegetables.",
        veg: false,
        egg: false,
      },
      {
        id: 305,
        name: "Baigan Bharta",
        price: 150,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Smoked and mashed eggplant dish.",
        veg: true,
        egg: false,
      },
      {
        id: 306,
        name: "Pakhala",
        price: 70,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "A fermented rice dish served chilled, perfect for a light meal.",
        veg: true,
        egg: false,
      },
      {
        id: 307,
        name: "Ghanta",
        price: 100,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Sweet pancakes made with rice flour and jaggery.",
        veg: true,
        egg: false,
      },
      {
        id: 308,
        name: "Chicken Curry",
        price: 280,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Spicy chicken curry cooked with onions, tomatoes, and Odia spices.",
        veg: false,
        egg: false,
      },
      {
        id: 309,
        name: "Dahi Aloo Dum",
        price: 180,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Potatoes cooked in a yogurt gravy with spices.",
        veg: true,
        egg: false,
      },
      {
        id: 310,
        name: "Santula",
        price: 250,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "A mixed vegetable dish cooked in a creamy cashew paste.",
        veg: true,
        egg: false,
      },
    ],
  },
  {
    id: 4,
    name: "The Zaika",
    image: require('../assets/images/dishes/download (2) (3).jpeg'),
    stars: 4.7,
    reviews: 3100,
    description:
      "The Zaika is a fine-dining restaurant offering North Indian cuisine in an elegant setting. They also have a selection of kebabs and biryanis.",
    category: "North Indian",
    address: "Sachen Bazar, Bhubaneswar",
    time: "7 PM - 11 PM",
    distance: "3.5 km",
    dishes: [
      {
        id: 401,
        name: "Butter Chicken",
        price: 380,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Tender chicken pieces cooked in a creamy tomato gravy.",
        veg: false,
        egg: true,
      },
      {
        id: 402,
        name: "Dal Makhani",
        price: 250,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Black lentil curry cooked with butter and cream.",
        veg: true,
        egg: true,
      },
      {
        id: 403,
        name: "Mutton Rogan Josh",
        price: 450,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Lamb curry cooked in a rich gravy with yogurt and spices.",
        veg: false,
        egg: false,
      },
      {
        id: 404,
        name: "Chicken Biryani",
        price: 320,
        image: "",
        description:
          "Fragrant rice dish layered with chicken, spices, and saffron.",
        veg: false,
        egg: true,
      },
      {
        id: 405,
        name: "Paneer Tikka Masala",
        price: 300,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Cottage cheese cubes marinated in spices and grilled, cooked in a creamy tomato gravy.",
        veg: true,
        egg: true,
      },
      {
        id: 406,
        name: "Garlic Naan",
        price: 80,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Leavened flatbread flavored with garlic butter.",
        veg: true,
        egg: false,
      },
      {
        id: 407,
        name: "Tandoori Roti",
        price: 60,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Whole wheat flatbread cooked in a tandoor oven.",
        veg: true,
        egg: false,
      },
      {
        id: 408,
        name: "Shahi Tukda",
        price: 220,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Fried bread pudding dipped in a creamy and sweet milk sauce.",
        veg: true,
        egg: true,
      },
      {
        id: 409,
        name: "Gulab Jamun",
        price: 150,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Deep-fried dough balls soaked in a rose-flavored sugar syrup.",
        veg: true,
        egg: false,
      },
      {
        id: 410,
        name: "Kheer",
        price: 180,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Rice pudding flavored with nuts and cardamom.",
        veg: true,
        egg: true,
      },
    ],
  },
  {
    id: 5,
    name: "Atithi Devo Bhaba",
    image: require('../assets/images/dishes/download (2) (3).jpeg'),
    stars: 4.3,
    reviews: 765,
    description:
      "Atithi Devo Bhaba is a restaurant specializing in authentic Odia cuisine with a focus on fresh, local ingredients and traditional cooking methods.",
    category: "Odia",
    address: "A/54, opposite Law University",
    time: "12 PM - 4 PM, 7 PM - 10 PM",
    distance: "2.0 km",
    dishes: [
      {
        id: 501,
        name: "Odia Thali",
        price: 250,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "A platter with a selection of Odia dishes like dal, rice, vegetables, chutney, and papad.",
        veg: true,
        egg: false,
      },
      {
        id: 502,
        name: "Chicken Takari",
        price: 300,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Spicy chicken curry cooked with vegetables and spices.",
        veg: false,
        egg: false,
      },
      {
        id: 503,
        name: "Dahibara Aloo Dum",
        price: 150,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Fried lentil dumplings served in a potato curry with yogurt.",
        veg: true,
        egg: false,
      },
      {
        id: 504,
        name: "Santula",
        price: 220,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "A mixed vegetable dish cooked in a creamy cashew paste.",
        veg: true,
        egg: false,
      },
      {
        id: 505,
        name: "Chhena Poda",
        price: 90,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "A baked cheese dessert flavored with cardamom and saffron.",
        veg: true,
        egg: false,
      },
      {
        id: 506,
        name: "Macha Ghanta",
        price: 280,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Fish cooked in a mustard and coconut gravy.",
        veg: false,
        egg: false,
      },
      {
        id: 507,
        name: "Khaman",
        price: 80,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "A steamed gram flour cake with a savory and tangy taste.",
        veg: true,
        egg: false,
      },
      {
        id: 508,
        name: "Pakhala",
        price: 60,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "A fermented rice dish served chilled, perfect for a light meal.",
        veg: true,
        egg: false,
      },
      {
        id: 509,
        name: "Baigan Chura",
        price: 120,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Sun-dried eggplant slices cooked with spices.",
        veg: true,
        egg: false,
      },
      {
        id: 510,
        name: "Aloo Potala Rasa",
        price: 180,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Potato and elephant foot yam curry cooked in a poppy seed paste.",
        veg: true,
        egg: false,
      },
    ],
  },
  {
    id: 6,
    name: "Wah Hing",
    image: require('../assets/images/dishes/download (2) (3).jpeg'),
    stars: 4.1,
    reviews: 1500,
    description:
      "Wah Hing is a popular restaurant serving Chinese cuisine with a focus on Sichuan and Cantonese dishes.",
    category: "Chinese",
    address: "Master Canteen Area",
    time: "11 AM - 10:30 PM",
    distance: "0.8 km",
    dishes: [
      {
        id: 601,
        name: "Kung Pao Chicken",
        price: 320,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Stir-fried chicken with peanuts, vegetables, and chili peppers.",
        veg: false,
        egg: true,
      },
      {
        id: 602,
        name: "Veg Hakka Noodles",
        price: 250,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Stir-fried noodles with vegetables in a light sauce.",
        veg: true,
        egg: true,
      },
      {
        id: 603,
        name: "Schezwan Fried Rice",
        price: 200,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Spicy fried rice with vegetables, chili peppers, and meat (optional).",
        veg: true,
        egg: true,
      },
      {
        id: 604,
        name: "Manchow Soup",
        price: 180,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Spicy and tangy vegetable soup with crispy noodles.",
        veg: true,
        egg: true,
      },
      {
        id: 605,
        name: "Spring Rolls",
        price: 150,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Crispy fried rolls filled with vegetables or meat (optional).",
        veg: true,
        egg: true,
      },
      {
        id: 606,
        name: "Honey Chilli Potato",
        price: 220,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Crispy fried potatoes tossed in a sweet and chili sauce.",
        veg: true,
        egg: true,
      },
      {
        id: 607,
        name: "Szechuan Chicken",
        price: 380,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Spicy chicken dish cooked in a Szechuan peppercorn sauce.",
        veg: false,
        egg: true,
      },
      {
        id: 608,
        name: "Hakka Chicken",
        price: 350,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Stir-fried chicken with vegetables and soy sauce.",
        veg: false,
        egg: true,
      },
      {
        id: 609,
        name: "Veg Manchurian",
        price: 280,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description:
          "Gobi Manchurian or cauliflower florets cooked in a sweet and chili sauce.",
        veg: true,
        egg: true,
      },
      {
        id: 610,
        name: "Egg Fried Rice",
        price: 180,
        image: require('../assets/images/dishes/download (2) (3).jpeg'),
        description: "Fried rice with scrambled eggs and vegetables.",
        veg: true,
      },
    ],
  },
];
